In [90]:
import pandas as pd

import string
import re
import nltk
import gensim


from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn import metrics

import xgboost as xgb
from sklearn.pipeline import Pipeline

In [91]:
df =pd.read_excel('dataset/saved_file.xlsx')
df

,Unnamed: 0,comment,uniqe_number
0,0,گوشی موبایل سامسونگ مدل Galaxy A13 64 گیگابایت...,0
1,1,موبایل سامسونگ مدل Galaxy A13 دو سیم کارت ظرف...,0
2,2,سامسونگ مدل Galaxy A13 64 گیگابایت,0
3,3,Galaxy A23 SM-A235,1
4,4,گوشی موبایل سامسونگ مدل Galaxy A23 SM-A235,1
...,...,...,...
292,292,دوربین چاپ سریع لوموگرافی مدل Automat Dahab,50
293,293,Automat Dahab,50
294,294,لوموگرافی,51
295,295,باتری قلمی و نیم قلمی کملیون,52
296,296,دوربین دیجیتال نوا تویز مدل XA720 طرح پپا,53

In [45]:
# ds =ds.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis = 1)

In [92]:
# nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [116]:
# stopwords =nltk.corpus.stopwords.words("english")

# def clean_data(text):

#   text ="".join([char for char in text if char not in string.punctuation]).lower()
#   token =re.split("\W+",text)
#   text =[word for word in token if word not in stopwords]

#   return text

# df['clean_comment'] =df['comment'].apply(clean_data)
# df

,Unnamed: 0,comment,uniqe_number,clean_comment
0,0,گوشی موبایل سامسونگ مدل Galaxy A13 64 گیگابایت...,0,"[گوشی, موبایل, سامسونگ, مدل, galaxy, a13, 64, ..."
1,1,موبایل سامسونگ مدل Galaxy A13 دو سیم کارت ظرف...,0,"[, موبایل, سامسونگ, مدل, galaxy, a13, دو, سیم,..."
2,2,سامسونگ مدل Galaxy A13 64 گیگابایت,0,"[سامسونگ, مدل, galaxy, a13, 64, گیگابایت]"
3,3,Galaxy A23 SM-A235,1,"[galaxy, a23, sma235]"
4,4,گوشی موبایل سامسونگ مدل Galaxy A23 SM-A235,1,"[گوشی, موبایل, سامسونگ, مدل, galaxy, a23, sma235]"
...,...,...,...,...
292,292,دوربین چاپ سریع لوموگرافی مدل Automat Dahab,50,"[دوربین, چاپ, سریع, لوموگرافی, مدل, automat, d..."
293,293,Automat Dahab,50,"[automat, dahab]"
294,294,لوموگرافی,51,[لوموگرافی]
295,295,باتری قلمی و نیم قلمی کملیون,52,"[باتری, قلمی, و, نیم, قلمی, کملیون, ]"
296,296,دوربین دیجیتال نوا تویز مدل XA720 طرح پپا,53,"[دوربین, دیجیتال, نوا, تویز, مدل, xa720, طرح, ..."

In [126]:
x_train ,x_test ,y_train ,y_test =train_test_split(df['comment'],df['uniqe_number'],random_state=42,test_size=0.3)

In [134]:
ensmble = Pipeline([
    ('bow', CountVectorizer()),
    ('tfid', TfidfTransformer()),
    ('model', xgb.XGBClassifier(
        learning_rate=0.1,
        max_depth=10,
        n_estimators=100,
        use_label_encoder=False,
        eval_metric='auc',
    ))
])

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")

In [127]:
ensmble.fit(x_train, y_train)

y_pred_class = ensmble.predict(x_test)
y_pred_train = ensmble.predict(x_train)

print('Train: {}'.format(metrics.accuracy_score(y_train, y_pred_train)))
print('Test: {}'.format(metrics.accuracy_score(y_test, y_pred_class)))

ensmble.score(x_test, y_test)

Train: 0.893719806763285
Test: 0.7777777777777778

0.7777777777777778

In [133]:
test_sample = ensmble.predict(['گوشی موبایل نوکیا 5710'])
test_sample

array([5])